import gymnasium as gym
import numpy as np
import pybullet as p
import pybullet_data
import math
import os
import random
from gymnasium import spaces
from PIL import Image

from goal_detector import GoalDetector
from maze_grid import (
    generate_5x5_maze,
    world_to_cell,
    cell_center,
    START_POS,
    GOAL_POS,
    GOAL_CELL,
    CELL_SIZE,
    WALL_HEIGHT,
    GRID_ROWS,
    GRID_COLS,
)

# ========================================================
# Environment constants
# ========================================================
GOAL_RADIUS      = 1.0
NUM_RAYS         = 24
RAY_LENGTH       = 3.0
RAY_START_H      = 0.15
MAX_STEPS        = 6000
CNN_VISION_RANGE = 10.0   # metres — skip camera render when farther than this

# Default reward config -- used if none passed in
DEFAULT_REWARD_CONFIG = {
    "goal_reward":         2000.0,
    "collision_penalty":    -500.0,
    "step_penalty":          -0.05,
    "progress_scale":         20.0,

    # Occupancy / visited-grid exploration signals
    "new_cell_reward":        0.5,    # one-time bonus on first entry — small so goal dominates
    "revisit_penalty":       -0.05,  # grows with visit count to push robot out of loops

    # CNN visual guidance — kept small so the robot doesn't drive through walls
    "cnn_visible_reward":     0.5,    # small bonus whenever the goal is visible
    "cnn_centering_reward":   1.5,    # bonus when goal is centred AND path ahead is clear

    # Front-wall early-warning penalty (fraction units: value × 3 m = actual metres)
    "front_wall_threshold":   0.50,   # 0.50 frac = 1.5 m — fire well before collision
    "front_wall_penalty":     3.0,    # peak penalty strength at zero distance

    # Near-wall exponential proximity penalty
    "proximity_threshold":    0.18,   # 0.18 frac = 0.54 m
    "proximity_penalty":     -0.5,
    "proximity_exponent":     3.0,
    "crash_lidar_threshold":  0.01,
}


class TurtleBot3MazeEnv(gym.Env):
    """
    PyBullet + TurtleBot3 Burger 5x5 grid-maze navigation environment.

    The maze is generated by maze_grid.generate_5x5_maze() which returns
    wall segments as (center_x, center_y, half_x, half_y) tuples.  Every
    segment spans exactly one cell edge so walls are fully continuous with
    no shortcut gaps.

    Grid layout (A-E columns left to right, 1-5 rows top to bottom):
        A1 B1 C1 D1 E1
        A2 B2 C2 D2 E2
        A3 B3 C3 D3 E3
        A4 B4 C4 D4 E4
        A5 B5 C5 D5 E5    <- robot starts here (A5 = bottom-left)
                      E1  <- goal is here      (E1 = top-right)

    Observation: 24 LiDAR rays + CNN goal detection (detected, confidence)
    Action:      left/right wheel velocities (continuous, -1 to 1)
    """
    metadata = {"render_modes": ["human"]}

    def __init__(self, renders=False, walls=None, reward_config=None,
                 maze_seed=42, randomize_maze=False):
        super().__init__()
        self.renders          = renders
        self._maze_seed       = maze_seed
        self._randomize_maze  = randomize_maze
        # walls=[...] -> explicit segments (test mode — never randomised)
        # walls=None  -> generate from seed; if randomize_maze=True, new seed each reset
        self._explicit_walls  = walls
        self._walls           = walls if walls is not None else generate_5x5_maze(maze_seed)
        self._physics    = None
        self._robot      = None
        self._wall_ids   = []
        self._step_count = 0
        self._prev_dist  = None

        # CNN detection cache -- only update every N steps for speed
        self._goal_detector    = GoalDetector()
        self._cnn_detected     = 0.0
        self._cnn_confidence   = 0.0
        self._cnn_offset       = 0.0   # horizontal offset of goal in camera [-1=left, +1=right]
        self._cnn_update_every = 10

        # Grid-cell visit tracking -- resets each episode
        self._visit_counts        = {}     # (row, col) -> int
        self._current_cell        = None   # (row, col) of robot right now
        self._just_entered_new_cell = False  # True for exactly one step on first entry

        # Load reward config
        cfg = reward_config if reward_config is not None else DEFAULT_REWARD_CONFIG
        self._goal_reward         = cfg["goal_reward"]
        self._collision_penalty   = cfg["collision_penalty"]
        self._step_penalty        = cfg["step_penalty"]
        self._progress_scale      = cfg["progress_scale"]
        self._proximity_threshold   = cfg["proximity_threshold"]
        self._proximity_penalty     = cfg["proximity_penalty"]
        self._proximity_exponent    = cfg.get("proximity_exponent", 3.0)
        self._crash_lidar_threshold = cfg.get("crash_lidar_threshold", 0.01)
        self._new_cell_reward       = cfg.get("new_cell_reward",  2.0)
        self._revisit_penalty       = cfg.get("revisit_penalty", -0.05)
        self._cnn_visible_reward    = cfg.get("cnn_visible_reward",   0.5)
        self._cnn_centering_reward  = cfg.get("cnn_centering_reward", 1.5)
        self._front_wall_threshold  = cfg.get("front_wall_threshold", 0.50)
        self._front_wall_penalty    = cfg.get("front_wall_penalty",   3.0)

        # Observation layout (52 values total):
        #   [0:24]  — 24 LiDAR ray hit-fractions
        #   [24]    — CNN detected flag (0/1)
        #   [25]    — CNN confidence (0-1)
        #   [26]    — CNN horizontal offset (-1=left, 0=centre, +1=right)
        #   [27:52] — 25 visited-cell binary flags (5x5 row-major)
        obs_size = NUM_RAYS + 3 + GRID_ROWS * GRID_COLS
        low  = np.zeros(obs_size, dtype=np.float32)
        high = np.ones(obs_size, dtype=np.float32)
        low[26]  = -1.0   # cnn_offset lower bound
        self.observation_space = spaces.Box(low=low, high=high, dtype=np.float32)
        self.action_space = spaces.Box(
            low =np.array([-1.0, -1.0], dtype=np.float32),
            high=np.array([ 1.0,  1.0], dtype=np.float32),
            dtype=np.float32,
        )

    # ----------------------------------------------------------
    # Public helper -- used by GUI for visited-cell overlay
    # ----------------------------------------------------------

    def get_visit_map(self):
        """Return {(row, col): visit_count} for the current episode."""
        return dict(self._visit_counts)

    # ----------------------------------------------------------

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        # Regenerate a fresh maze each episode during training so the policy
        # learns generalizable navigation rather than memorising one layout.
        if self._randomize_maze and self._explicit_walls is None:
            self._walls = generate_5x5_maze(random.randint(0, 99999))

        if self._physics is not None:
            p.disconnect(self._physics)

        self._physics = p.connect(p.GUI if self.renders else p.DIRECT)

        if self.renders:
            p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0,
                                       physicsClientId=self._physics)
            p.resetDebugVisualizerCamera(
                cameraDistance=12,
                cameraYaw=0,
                cameraPitch=-60,
                cameraTargetPosition=[0, 0, 0],
                physicsClientId=self._physics,
            )

        p.setAdditionalSearchPath(pybullet_data.getDataPath(),
                                  physicsClientId=self._physics)
        p.setGravity(0, 0, -9.81, physicsClientId=self._physics)

        ground = p.loadURDF("plane.urdf", physicsClientId=self._physics)
        texture_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    "dirt.jpg")
        if os.path.exists(texture_path):
            texture_id = p.loadTexture(texture_path,
                                       physicsClientId=self._physics)
            p.changeVisualShape(ground, -1,
                                textureUniqueId=texture_id,
                                rgbaColor=[1, 1, 1, 1],
                                physicsClientId=self._physics)
        else:
            p.changeVisualShape(ground, -1,
                                textureUniqueId=-1,
                                rgbaColor=[0.35, 0.22, 0.08, 1],
                                physicsClientId=self._physics)

        urdf_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "turtlebot3_burger.urdf")
        self._robot = p.loadURDF(
            urdf_path, START_POS,
            p.getQuaternionFromEuler([0, 0, 0]),
            flags=p.URDF_USE_INERTIA_FROM_FILE,
            physicsClientId=self._physics,
        )

        # ── Hedge walls (continuous segment-based) ───────────────
        # Each wall is a single box spanning one full cell edge.
        # (cx, cy, hx, hy) from generate_5x5_maze() are placed at
        # world position (cx, cy, WALL_HEIGHT/2).
        HEDGE_H  = WALL_HEIGHT
        HEDGE_HZ = HEDGE_H / 2.0

        self._wall_ids = []
        for (cx, cy, hx, hy) in self._walls:
            col_shape = p.createCollisionShape(
                p.GEOM_BOX,
                halfExtents=[hx, hy, HEDGE_HZ],
                physicsClientId=self._physics,
            )
            vis_shape = p.createVisualShape(
                p.GEOM_BOX,
                halfExtents=[hx, hy, HEDGE_HZ],
                rgbaColor=[0.10, 0.42, 0.10, 1],
                physicsClientId=self._physics,
            )
            body_id = p.createMultiBody(
                0, col_shape, vis_shape,
                [cx, cy, HEDGE_HZ],
                physicsClientId=self._physics,
            )
            self._wall_ids.append(body_id)

            # Dark trim cap on top -- aesthetic only, no collision
            trim_vis = p.createVisualShape(
                p.GEOM_BOX,
                halfExtents=[hx + 0.02, hy + 0.02, 0.04],
                rgbaColor=[0.06, 0.28, 0.06, 1],
                physicsClientId=self._physics,
            )
            p.createMultiBody(
                0, -1, trim_vis,
                [cx, cy, HEDGE_H + 0.04],
                physicsClientId=self._physics,
            )

        # ── Cabin (goal) ─────────────────────────────────────────
        gx, gy = GOAL_POS[0], GOAL_POS[1]

        # Cabin is visual-only (collisionShapeIndex=-1) so LiDAR rays pass through
        # it and the robot is never penalised for approaching its own goal.
        cabin_vis = p.createVisualShape(
            p.GEOM_BOX, halfExtents=[0.3, 0.3, 0.25],
            rgbaColor=[0.36, 0.18, 0.09, 1],
            physicsClientId=self._physics)
        cabin_body = p.createMultiBody(
            0, -1, cabin_vis,
            [gx, gy, 0.25],
            physicsClientId=self._physics)
        p.changeVisualShape(cabin_body, -1,
                            rgbaColor=[0.36, 0.18, 0.09, 1],
                            physicsClientId=self._physics)

        roof_vis = p.createVisualShape(
            p.GEOM_BOX, halfExtents=[0.35, 0.35, 0.15],
            rgbaColor=[0.4, 0.06, 0.06, 1],
            physicsClientId=self._physics)
        roof_body = p.createMultiBody(
            0, -1, roof_vis,
            [gx, gy, 0.65],
            physicsClientId=self._physics)
        p.changeVisualShape(roof_body, -1,
                            rgbaColor=[0.4, 0.06, 0.06, 1],
                            physicsClientId=self._physics)

        # Tall green beacon -- visible to the forward camera from
        # several metres away so the CNN has a useful detection range.
        beacon_vis = p.createVisualShape(
            p.GEOM_CYLINDER, radius=0.75, length=WALL_HEIGHT,
            rgbaColor=[0.0, 1.0, 0.0, 1.0],
            physicsClientId=self._physics)
        p.createMultiBody(0, -1, beacon_vis,
                          [gx, gy, WALL_HEIGHT / 2],
                          physicsClientId=self._physics)

        # Square floor tile covering the entire E1 cell (CELL_SIZE × CELL_SIZE = 2 m × 2 m)
        half = CELL_SIZE / 2.0   # 1.0 m
        goal_vis = p.createVisualShape(
            p.GEOM_BOX, halfExtents=[half, half, 0.01],
            rgbaColor=[0.0, 1.0, 0.0, 0.3],
            physicsClientId=self._physics)
        p.createMultiBody(0, -1, goal_vis,
                          [gx, gy, 0.01],
                          physicsClientId=self._physics)

        # ── Reset per-episode state ──────────────────────────────
        self._cnn_detected   = 0.0
        self._cnn_confidence = 0.0
        self._cnn_offset     = 0.0
        self._step_count     = 0
        self._prev_dist      = self._dist_to_goal()

        # Reset visited-cell map; mark spawn cell as visited once
        self._visit_counts          = {}
        self._just_entered_new_cell = False
        self._current_cell = world_to_cell(float(START_POS[0]),
                                           float(START_POS[1]))
        self._visit_counts[self._current_cell] = 1

        return self._get_obs(), {}

    def step(self, action):
        self._apply_action(action)

        reached_goal = False
        for _ in range(10):
            p.stepSimulation(physicsClientId=self._physics)

            if self._dist_to_goal() < GOAL_RADIUS:
                reached_goal = True
                break
            if self._check_collision():
                break

        self._step_count += 1

        dist = self._dist_to_goal()

        # ── Track which 5x5 grid cell the robot occupies ─────────
        pos, _ = p.getBasePositionAndOrientation(
            self._robot, physicsClientId=self._physics)
        new_cell = world_to_cell(float(pos[0]), float(pos[1]))
        self._just_entered_new_cell = False
        if new_cell != self._current_cell:
            self._just_entered_new_cell = new_cell not in self._visit_counts
            self._current_cell = new_cell
            self._visit_counts[new_cell] = (
                self._visit_counts.get(new_cell, 0) + 1
            )

        # Cell-based goal check — the whole E1 cell counts as success so the
        # robot doesn't need to hit the small circular zone exactly.
        if not reached_goal and self._current_cell == GOAL_CELL:
            reached_goal = True

        lidar     = self._get_lidar()
        min_ray   = float(np.min(lidar))

        physical_collision = self._check_collision()
        lidar_collision    = min_ray < self._crash_lidar_threshold
        collision          = physical_collision or lidar_collision

        reward = self._compute_reward(dist, reached_goal, collision, action)
        self._prev_dist = dist

        terminated = reached_goal or collision
        truncated  = self._step_count >= MAX_STEPS

        info = {
            "reached_goal":      reached_goal,
            "collision":         collision,
            "physical_collision": physical_collision,
            "lidar_collision":   lidar_collision,
            "dist":              dist,
            "min_lidar":         min_ray,
            "current_cell":      self._current_cell,
        }

        return self._get_obs(), reward, terminated, truncated, info

    def render(self):
        pass

    def close(self):
        if self._physics is not None:
            p.disconnect(self._physics)
            self._physics = None

    # ----------------------------------------------------------
    def _apply_action(self, action):
        max_vel   = 15.0
        left_vel  = -float(action[0]) * max_vel
        right_vel = -float(action[1]) * max_vel

        # Limit turn rate -- prevents sharp 360 spins
        diff = left_vel - right_vel
        if abs(diff) > 8.0:
            avg       = (left_vel + right_vel) / 2.0
            sign      = 1 if diff > 0 else -1
            left_vel  = avg + 4.0 * sign
            right_vel = avg - 4.0 * sign

        for i in range(p.getNumJoints(self._robot,
                                      physicsClientId=self._physics)):
            name = p.getJointInfo(self._robot, i,
                                  physicsClientId=self._physics)[1].decode()
            if "left" in name and "wheel" in name:
                p.setJointMotorControl2(self._robot, i,
                    p.VELOCITY_CONTROL, targetVelocity=left_vel, force=8.0,
                    physicsClientId=self._physics)
            if "right" in name and "wheel" in name:
                p.setJointMotorControl2(self._robot, i,
                    p.VELOCITY_CONTROL, targetVelocity=right_vel, force=8.0,
                    physicsClientId=self._physics)

    def _get_lidar(self):
        pos, orn = p.getBasePositionAndOrientation(self._robot,
                                                   physicsClientId=self._physics)
        yaw = p.getEulerFromQuaternion(orn)[2]
        ray_from, ray_to = [], []
        for i in range(NUM_RAYS):
            angle = yaw + (2 * math.pi * i / NUM_RAYS)
            ray_from.append([pos[0], pos[1], RAY_START_H])
            ray_to.append([pos[0] + math.cos(angle) * RAY_LENGTH,
                           pos[1] + math.sin(angle) * RAY_LENGTH,
                           RAY_START_H])
        return np.array(
            [h[2] for h in p.rayTestBatch(ray_from, ray_to,
                                          physicsClientId=self._physics)],
            dtype=np.float32,
        )

    def _get_camera_frame(self):
        """Render robot POV camera frame and return as PIL image."""
        pos, orn = p.getBasePositionAndOrientation(
            self._robot, physicsClientId=self._physics)
        yaw = p.getEulerFromQuaternion(orn)[2]

        eye    = [pos[0], pos[1], pos[2] + 0.15]
        target = [pos[0] + math.cos(yaw),
                  pos[1] + math.sin(yaw),
                  pos[2] + 0.15]
        view = p.computeViewMatrix(
            cameraEyePosition    = eye,
            cameraTargetPosition = target,
            cameraUpVector       = [0, 0, 1],
            physicsClientId      = self._physics,
        )
        proj = p.computeProjectionMatrixFOV(
            fov=90, aspect=4/3, nearVal=0.05, farVal=10,
            physicsClientId=self._physics,
        )
        _, _, rgb, _, _ = p.getCameraImage(
            160, 120, view, proj,
            physicsClientId=self._physics,
        )
        arr = np.array(rgb, dtype=np.uint8).reshape(120, 160, 4)
        return Image.fromarray(arr, "RGBA").convert("RGB")

    def _get_obs(self):
        lidar = self._get_lidar()

        # CNN goal detection -- cached every N steps, and only rendered when
        # the robot is close enough for the goal to plausibly be in view.
        # Beyond CNN_VISION_RANGE the goal is always behind walls, so the
        # camera would return 0/0 anyway -- skipping saves the render cost.
        if self._step_count % self._cnn_update_every == 0:
            if self._dist_to_goal() < CNN_VISION_RANGE:
                frame                    = self._get_camera_frame()
                detected, conf, bbox     = self._goal_detector.detect(frame)
                self._cnn_detected       = 1.0 if detected else 0.0
                self._cnn_confidence     = float(conf)
                # Horizontal offset: bbox centre relative to image centre, normalised to [-1, 1]
                # bbox = (x1, y1, x2, y2) in original 160-px-wide image coordinates
                if detected and bbox is not None:
                    cx = (bbox[0] + bbox[2]) / 2.0
                    self._cnn_offset = float(np.clip((cx - 80.0) / 80.0, -1.0, 1.0))
                else:
                    self._cnn_offset = 0.0
            else:
                self._cnn_detected   = 0.0
                self._cnn_confidence = 0.0
                self._cnn_offset     = 0.0

        # Frontier / visited-cell map -- 25 binary flags in row-major order.
        # 0.0 = cell never entered this episode (frontier / unexplored)
        # 1.0 = cell entered at least once    (visited / explored)
        # The policy uses this to avoid re-entering already-explored dead ends
        # and to navigate toward unvisited frontiers without any GPS signal.
        visited_vec = np.zeros(GRID_ROWS * GRID_COLS, dtype=np.float32)
        for (r, c) in self._visit_counts:
            visited_vec[r * GRID_COLS + c] = 1.0

        return np.concatenate([
            lidar,
            [self._cnn_detected,
             self._cnn_confidence,
             self._cnn_offset],
            visited_vec,
        ]).astype(np.float32)

    def _dist_to_goal(self):
        pos, _ = p.getBasePositionAndOrientation(self._robot,
                                                 physicsClientId=self._physics)
        return math.sqrt((pos[0] - GOAL_POS[0])**2 +
                         (pos[1] - GOAL_POS[1])**2)

    def _check_collision(self):
        for wid in self._wall_ids:
            if p.getContactPoints(self._robot, wid,
                                  physicsClientId=self._physics):
                return True
        return False

    def _compute_reward(self, dist, reached_goal, collision, action):
        reward = self._step_penalty

        # ── Progress reward ──────────────────────────────────────
        progress = self._prev_dist - dist
        reward  += self._progress_scale * progress

        # ── Goal bonus + path efficiency ─────────────────────────
        # Efficiency bonus scales linearly with steps remaining so fast
        # routes pay significantly more than slow ones.
        # Fast (300/1500 steps):  base 1000 + 800 bonus = 1800
        # Slow (1400/1500 steps): base 1000 +  67 bonus = 1067
        if reached_goal:
            steps_remaining   = MAX_STEPS - self._step_count
            efficiency_bonus  = self._goal_reward * (steps_remaining / MAX_STEPS)
            reward += self._goal_reward + efficiency_bonus

        # ── Collision penalty ────────────────────────────────────
        if collision:
            reward += self._collision_penalty

        # ── Exponential proximity penalty ────────────────────────
        lidar   = self._get_lidar()
        min_ray = float(np.min(lidar))

        if min_ray < self._proximity_threshold:
            closeness = np.clip(
                1.0 - (min_ray / self._proximity_threshold), 0.0, 1.0)
            exponential_penalty = math.exp(
                self._proximity_exponent * closeness) - 1.0
            reward += self._proximity_penalty * exponential_penalty

        # ── Directional wall-avoidance penalty ───────────────────
        left_wheel  = float(action[0])
        right_wheel = float(action[1])
        turn_value  = right_wheel - left_wheel

        front_dist = float(np.mean(np.concatenate([lidar[0:3], lidar[21:24]])))
        left_dist  = float(np.mean(lidar[5:10]))
        right_dist = float(np.mean(lidar[14:19]))

        # ── Front-wall early-warning penalty ─────────────────────
        # Configurable threshold gives the robot enough reaction time at dead ends.
        # Separate from the left/right avoidance so it can be tuned independently.
        fwt = self._front_wall_threshold
        if front_dist < fwt:
            closeness = np.clip(1.0 - (front_dist / fwt), 0.0, 1.0)
            reward -= self._front_wall_penalty * closeness

        # ── Side-wall avoidance — penalise turning into a close wall ──
        if left_dist < fwt and turn_value < 0.0:
            closeness = np.clip(1.0 - (left_dist / fwt), 0.0, 1.0)
            reward -= 3.0 * closeness * abs(turn_value)

        if right_dist < fwt and turn_value > 0.0:
            closeness = np.clip(1.0 - (right_dist / fwt), 0.0, 1.0)
            reward -= 3.0 * closeness * abs(turn_value)

        # ── Corridor centering ────────────────────────────────────
        # Only fires when walls visible both sides (corridor), not open space.
        if left_dist < 0.45 and right_dist < 0.45:
            reward -= 0.3 * abs(left_dist - right_dist)

        # ── Front-clear flag (used by CNN gating below) ───────────
        # True when the path directly ahead has no wall within 1.35 m.
        front_clear = front_dist > 0.45

        # ── Motion rewards ────────────────────────────────────────
        _, orn = p.getBasePositionAndOrientation(
            self._robot, physicsClientId=self._physics)
        yaw = p.getEulerFromQuaternion(orn)[2]

        linear_vel, angular_vel = p.getBaseVelocity(
            self._robot, physicsClientId=self._physics)
        angular_speed  = abs(angular_vel[2])
        signed_forward = (linear_vel[0] * math.cos(yaw) +
                          linear_vel[1] * math.sin(yaw))
        forward_speed  = abs(signed_forward)

        # ── CNN visual guidance — wall-aware ─────────────────────
        # Small reward just for seeing the goal (visibility signal).
        # Centering reward only applies when the path ahead is actually clear —
        # if a wall blocks the direct route the robot should NOT be rewarded for
        # driving straight toward the visible-but-unreachable goal.
        if self._cnn_detected > 0.5:
            reward += self._cnn_visible_reward
            if front_clear:
                # Goal centred in camera (+max) vs offset to one side (+less)
                reward += self._cnn_centering_reward * (1.0 - abs(self._cnn_offset))

                # Turn-away penalty: if goal is right and robot steers left, small penalty
                # (and vice-versa). Only when front is clear — don't penalise corridor turns.
                goal_on_right = self._cnn_offset > 0.25
                goal_on_left  = self._cnn_offset < -0.25
                if goal_on_right and turn_value < -0.3:
                    reward -= 0.4 * abs(turn_value)
                if goal_on_left and turn_value > 0.3:
                    reward -= 0.4 * abs(turn_value)
        elif signed_forward > 0.2:
            reward += 0.05   # small base exploration bonus when goal not visible

        # Penalise driving in reverse
        if signed_forward < -0.1:
            reward -= 0.2 * min(abs(signed_forward), 3.0)

        # Anti-spin penalty
        if angular_speed > 1.5:
            reward -= 0.2 * (angular_speed ** 2)
        if angular_speed > 1.5 and forward_speed < 0.3:
            reward -= 0.5 * angular_speed

        # ── Visited-grid exploration signals ─────────────────────
        # One-time bonus the first step the robot enters a new cell.
        # Kept small relative to goal_reward (+1000) so exploration is
        # an incentive, not a dominant objective.
        if self._just_entered_new_cell:
            reward += self._new_cell_reward

        # Growing revisit penalty — scales with how many times this cell has
        # been visited, capped at 10× so it doesn't spiral out of control.
        # 1st revisit: -0.05 · 2 = -0.10 / step
        # 5th revisit: -0.05 · 6 = -0.30 / step
        # 10th+ :      -0.05 · 10 = -0.50 / step (cap)
        visit_count = self._visit_counts.get(self._current_cell, 0)
        if visit_count > 1:
            reward += self._revisit_penalty * min(visit_count, 10)

        return reward
